# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - PortfolioV1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore PortfolioV1.slnx

      - name: Build application
        run: dotnet build PortfolioV1.slnx --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_76C852FD757048B28A5AB197689FE42C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EC53DF0A679A418F9E9548B6641B67E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_095194D44A53444EABFA634977787D56 }}
      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef --version 8.*
          
      - name: Update database with EF Core migrations
        run: dotnet ef database update --project PortfolioV1/PortfolioV1.csproj --startup-project PortfolioV1/PortfolioV1.csproj
        env:
          ASPNETCORE_ENVIRONMENT: Production

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PortfolioV1'
          slot-name: 'Production'
          package: .
          